version: '3'

services: 
  server:
    build: 
      context: ./Servidor
    command: python HeadNode.py
    ports:
      - "5000:5000"
    volumes:
      - .:/Servidor
    stdin_open: true
    tty: true

  data:
    build:
      context: ./Almacenamiento
    command: python DataNode.py
    volumes:
      - .:/Almacenamiento
    links:
      - "server"
    depends_on:
      - server

  client:
    build:
      context: ./Cliente
    command: python Cliente.py
    volumes:
      - .:/Cliente
    links:
      - "server"
    depends_on:
      - data
      - server